services: 
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      ENCODING: UTF-8
      POSTGRES_DB: pluto_dev
      PGDATA: /var/lib/postgresql/data/pgdata

    volumes: 
      - pgdata:/var/lib/postgresql/data

    ports:
      - "4230:5432"

volumes: 
  pgdata: 